# Generated by Django 4.2 on 2025-07-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_id', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=7)),
                ('people_helped', models.IntegerField()),
                ('events_conducted', models.IntegerField()),
                ('funds_utilized', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ngo_id', 'month')},
            },
        ),
    ]
