# Generated by Django 4.2.7 on 2025-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='report',
            name='ngo_id',
            field=models.CharField(max_length=100),
        ),
    ]
